
const authorizationType = {
    SET_SCHOOL_DATA:"SET_SCHOOL_DATA",
    EDIT_SCHOOL_DATA:"EDIT_SCHOOL_DATA",
    DELETE_SCHOOL_DATA:"DELETE_SCHOOL_DATA",
    CHECK_SCHOOL_DATA:"CHECK_SCHOOL_DATA",
    REGISTER_DATA:"REGISTER_DATA",
    GET_LOGIN_KEY:"GET_LOGIN_KEY",
    CHECK_LOGIN_KEY:"CHECK_LOGIN_KEY",
    SET_TEACHER_DATA:"SET_TEACHER_DATA",
    EDIT_TEACHER_DATA:"EDIT_TEACHER_DATA",
    DELETE_TEACHER_DATA:"DELETE_TEACHER_DATA",
    CHECK_TEACHER_DATA:"CHECK_TEACHER_DATA",
    SET_CHILDREN_DATA:"SET_CHILDREN_DATA",
    EDIT_CHILDREN_DATA:"EDIT_CHILDREN_DATA",
    DELETE_CHILDREN_DATA:"DELETE_CHILDREN_DATA",
    CHECK_CHILDREN_DATA:"CHECK_CHILDREN_DATA",







}
export default authorizationType